<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ElevatorControl.Services.Interfaces\ElevatorControl.Services.Interfaces.csproj" />
    <ProjectReference Include="..\ElevatorControl.Domain\ElevatorControl.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
